/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.stack.core.security;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.security.KeyPair;
import java.util.List;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.operator.jcajce.JcaContentVerifierProviderBuilder;
import org.bouncycastle.pkcs.PKCS10CertificationRequest;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.junit.jupiter.api.Test;

class RsaSha256CertificateFactoryTest {

  // Brainpool P-384 keys are generated by BC, so CSR signing and verification must stay on a
  // provider that understands the Brainpool curve.
  @Test
  void brainpoolP384SigningRequestUsesBouncyCastleProvider() throws Exception {
    TestCertificateFactory factory = new TestCertificateFactory();
    KeyPair keyPair = factory.createEccBrainpoolP384r1KeyPair();

    ByteString csrBytes =
        factory.createSigningRequest(
            NodeIds.EccBrainpoolP384r1ApplicationCertificateType,
            keyPair,
            new X500Name("CN=brainpool-p384"),
            "urn:eclipse:milo:test",
            List.of("localhost"),
            List.of("127.0.0.1"));
    PKCS10CertificationRequest csr = new PKCS10CertificationRequest(csrBytes.bytesOrEmpty());

    assertTrue(
        csr.isSignatureValid(
            new JcaContentVerifierProviderBuilder()
                .setProvider(new BouncyCastleProvider())
                .build(csr.getSubjectPublicKeyInfo())));
  }
}
