/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.server.conditions;

import static java.util.Objects.requireNonNull;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ubyte;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.uint;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ushort;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscription;
import org.eclipse.milo.opcua.sdk.core.Reference;
import org.eclipse.milo.opcua.sdk.server.nodes.UaObjectNode;
import org.eclipse.milo.opcua.sdk.test.AbstractClientServerTest;
import org.eclipse.milo.opcua.sdk.test.EventTestSupport;
import org.eclipse.milo.opcua.sdk.test.TestNamespace;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.OpcUaDataType;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.types.builtin.DataValue;
import org.eclipse.milo.opcua.stack.core.types.builtin.LocalizedText;
import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import org.eclipse.milo.opcua.stack.core.types.builtin.Variant;
import org.eclipse.milo.opcua.stack.core.types.enumerated.TimestampsToReturn;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodRequest;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodResult;
import org.eclipse.milo.opcua.stack.core.types.structured.CallResponse;
import org.eclipse.milo.opcua.stack.core.types.structured.EventFilter;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * ClientUserId conformance for clients that carry no user identity.
 *
 * <p>ClientUserId is a mandatory String Property of ConditionType (Part 9 §5.5.2), while {@code
 * Session.getClientUserId()} is {@code null} for an AnonymousIdentityToken (OPC 10000-5 §6.4.3).
 * The default client identity provider here is anonymous — as is the OPC Foundation CTT's — so
 * these tests exercise exactly the path that made a Condition report a Null-typed ClientUserId for
 * the rest of its life after its first Acknowledge, Confirm, or AddComment.
 */
public class ConditionAnonymousUserTest extends AbstractClientServerTest {

  /** Severity of all events generated by the test condition; the where clause matches on it. */
  private static final int TEST_SEVERITY = 557;

  private AcknowledgeableCondition condition;
  private NodeId conditionId;

  @Override
  protected void configureTestNamespace(TestNamespace namespace) {
    namespace.configure(
        (context, nodeManager) -> {
          var source =
              new UaObjectNode(
                  context,
                  newNodeId("ConditionAnonymousUserTest/Source"),
                  newQualifiedName("ConditionAnonymousUserTest/Source"),
                  LocalizedText.english("ConditionAnonymousUserTest/Source"),
                  LocalizedText.NULL_VALUE,
                  uint(0),
                  uint(0),
                  ubyte(0));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasTypeDefinition,
                  NodeIds.BaseObjectType.expanded(),
                  true));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasComponent,
                  NodeIds.ObjectsFolder.expanded(),
                  Reference.Direction.INVERSE));

          nodeManager.addNode(source);

          try {
            condition =
                AcknowledgeableCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionAnonymousUserTest/Condition"))
                            .browseName(newQualifiedName("AnonymousUserCondition"))
                            .conditionSource(source)
                            .severity(ushort(TEST_SEVERITY))
                            .withConfirm());
          } catch (UaException e) {
            throw new RuntimeException(e);
          }

          server.getConditionManager().register(condition);
          conditionId = condition.getConditionId();
        });
  }

  @BeforeEach
  void resetConditionState() {
    condition.setConfirmed(true);
    condition.setAcked(true);
  }

  /**
   * A Condition instantiated from ConditionType inherits the declaration's Null value for
   * ClientUserId, so the Property would read the wrong DataType before any operator method is
   * called at all.
   */
  @Test
  void clientUserIdReadsAsAStringBeforeAnyOperatorAction() throws Exception {
    assertStringValued(readClientUserId(), "at rest");
  }

  /**
   * The CTT failure this test pins down: after an anonymous Acknowledge the Property read
   * "Unexpected mandatory datatype ... Expected 12 Actual 0" — a Null Variant where a String is
   * required — and stayed that way for the life of the Condition.
   */
  @Test
  void anonymousAcknowledgeLeavesClientUserIdAStringValue() throws Exception {
    condition.setAcked(false);

    CallMethodResult acknowledge =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(condition.currentBranch().getLastEventId()),
            new Variant(LocalizedText.english("acked anonymously")));
    assertTrue(requireNonNull(acknowledge.getStatusCode()).isGood());

    assertStringValued(readClientUserId(), "after Acknowledge");
  }

  @Test
  void anonymousConfirmLeavesClientUserIdAStringValue() throws Exception {
    condition.setAcked(false);

    CallMethodResult acknowledge =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(condition.currentBranch().getLastEventId()),
            new Variant(LocalizedText.NULL_VALUE));
    assertTrue(requireNonNull(acknowledge.getStatusCode()).isGood());

    // Acknowledge reports the newly confirmable state with its own EventId.
    CallMethodResult confirm =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Confirm,
            new Variant(condition.currentBranch().getLastEventId()),
            new Variant(LocalizedText.english("confirmed anonymously")));
    assertTrue(requireNonNull(confirm.getStatusCode()).isGood());

    assertStringValued(readClientUserId(), "after Confirm");
  }

  @Test
  void anonymousAddCommentLeavesClientUserIdAStringValue() throws Exception {
    condition.setAcked(false);

    CallMethodResult addComment =
        call(
            conditionId,
            NodeIds.ConditionType_AddComment,
            new Variant(condition.currentBranch().getLastEventId()),
            new Variant(LocalizedText.english("commented anonymously")));
    assertTrue(requireNonNull(addComment.getStatusCode()).isGood());

    assertStringValued(readClientUserId(), "after AddComment");
  }

  /**
   * The CTT reads ClientUserId as an <i>event field</i>, and the reported DataType is that of the
   * Variant the field carries — so the value that reaches subscribers must be a String too, not
   * only the one a Read returns.
   */
  @Test
  void eventsAfterAnAnonymousAcknowledgeCarryAStringClientUserId() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      EventFilter eventFilter =
          EventTestSupport.severityEventFilter(
              TEST_SEVERITY,
              EventTestSupport.eventField(NodeIds.BaseEventType, "Message"),
              EventTestSupport.eventField(NodeIds.ConditionType, "ClientUserId"));

      List<Variant[]> events =
          EventTestSupport.monitorEvents(subscription, NodeIds.Server, eventFilter);

      condition.setAcked(false);
      EventTestSupport.awaitEvent(
          events, "initial unacknowledged event", e -> "Unacknowledged".equals(messageOf(e)));

      CallMethodResult acknowledge =
          call(
              conditionId,
              NodeIds.AcknowledgeableConditionType_Acknowledge,
              new Variant(condition.currentBranch().getLastEventId()),
              new Variant(LocalizedText.english("acked anonymously")));
      assertTrue(requireNonNull(acknowledge.getStatusCode()).isGood());

      Variant[] acknowledged =
          EventTestSupport.awaitEvent(
              events, "acknowledged event", e -> "Acknowledged".equals(messageOf(e)));

      assertInstanceOf(
          String.class,
          acknowledged[1].value(),
          "ClientUserId event field must carry a String, not a Null Variant");
    } finally {
      subscription.delete();
    }
  }

  /**
   * An anonymous action must not keep reporting the previous, named operator: ClientUserId
   * identifies who performed the last operator action (§5.5.2), so retaining "operator1" would
   * misattribute the anonymous Acknowledge below.
   */
  @Test
  void anonymousAcknowledgeDisplacesAPreviouslyRecordedUserId() throws Exception {
    condition.setComment(LocalizedText.english("earlier note"), "operator1");
    assertEquals("operator1", condition.getNode().getClientUserId());

    condition.setAcked(false);

    CallMethodResult acknowledge =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(condition.currentBranch().getLastEventId()),
            new Variant(LocalizedText.english("acked anonymously")));
    assertTrue(requireNonNull(acknowledge.getStatusCode()).isGood());

    assertEquals("", condition.getNode().getClientUserId());
  }

  private DataValue readClientUserId() throws Exception {
    NodeId clientUserIdNodeId =
        requireNonNull(condition.getNode().getClientUserIdNode()).getNodeId();

    return client.readValue(0.0, TimestampsToReturn.Both, clientUserIdNodeId);
  }

  /**
   * Assert the read value is a String — the CTT reports this as "Expected 12 Actual 0" when the
   * Variant is Null, so both the DataType and the Java value are checked.
   */
  private static void assertStringValued(DataValue value, String description) {
    assertTrue(requireNonNull(value.getStatusCode()).isGood(), description);
    assertEquals(
        OpcUaDataType.String,
        value.value().getDataType().orElse(null),
        description + ": ClientUserId must be a String, not a Null Variant");
    assertInstanceOf(String.class, value.value().value(), description);
  }

  private CallMethodResult call(NodeId objectId, NodeId methodId, Variant... inputs)
      throws Exception {

    CallResponse response = client.call(List.of(new CallMethodRequest(objectId, methodId, inputs)));

    return requireNonNull(response.getResults())[0];
  }

  private static @Nullable String messageOf(Variant[] eventFields) {
    return eventFields[0].value() instanceof LocalizedText text ? text.text() : null;
  }
}
