/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.pubsub.server;

import java.security.SecureRandom;
import java.time.Duration;
import java.time.InstantSource;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.NavigableSet;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import org.eclipse.milo.opcua.sdk.pubsub.config.PubSubConfigValidationException;
import org.eclipse.milo.opcua.sdk.pubsub.config.SecurityGroupConfig;
import org.eclipse.milo.opcua.sdk.pubsub.security.PubSubSecurityPolicy;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Server-side key store backing the {@code GetSecurityKeys} face: generates, rotates, and serves
 * key material for the locally configured SecurityGroups.
 *
 * <p>The store is scheduler-free. Per Part 14 §8.3.2 the SecurityTokenId "starts at 1 and is
 * incremented by 1 each time KeyLifetime elapses even if no keys are requested", so the token id is
 * a pure function of time: {@code currentTokenId(now) = 1 + elapsed(now) / keyLifetime}, with the
 * rotation base recorded once at construction. Keys are generated lazily when a request first
 * touches their token id and cached so repeated requests for a token id inside the retention window
 * return byte-identical key data (callers dedup by FirstTokenId); entries older than {@code
 * currentTokenId - maxPastKeyCount} are pruned on access.
 *
 * <p>Key material is generated by a store-owned {@link SecureRandom} by default. {@code
 * NonceUtil.generateNonce} is deliberately not used: it silently falls back to {@code
 * ThreadLocalRandom} while its shared {@code SecureRandom} is seeding, which is unacceptable for
 * key material. Both the {@link InstantSource} and the {@link KeyGenerator} are injectable for test
 * determinism.
 *
 * <p>Zeroization: keys are held as immutable {@link ByteString}s and are never wiped; the Phase 4
 * zeroization posture confines wiping to {@code SecurityKeyMaterial} on the consuming side.
 *
 * <p>Thread safety: the group map is an immutable map held in a volatile field, swapped atomically
 * by {@link #replaceGroups} (the SKS refresh hook, serialized by the managed runtime); each group's
 * mutable state is synchronized, so concurrent Calls on the server's service threads are safe.
 */
final class SecurityGroupKeyStore {

  private static final Logger LOGGER = LoggerFactory.getLogger(SecurityGroupKeyStore.class);

  /** The default key lifetime applied when a SecurityGroup's configured lifetime is unusable. */
  static final Duration DEFAULT_KEY_LIFETIME = Duration.ofHours(1);

  /** The largest token id servable: FirstTokenId is a UInt32 on the wire. */
  private static final long MAX_TOKEN_ID = 0xFFFF_FFFFL;

  private volatile Map<String, GroupState> groups;
  private final InstantSource instantSource;
  private final KeyGenerator keyGenerator;

  /**
   * Create a store serving {@code securityGroups}, with the system clock and a store-owned {@link
   * SecureRandom} key generator.
   */
  SecurityGroupKeyStore(List<SecurityGroupConfig> securityGroups) {
    this(securityGroups, InstantSource.system(), secureRandomKeyGenerator());
  }

  /**
   * Create a store serving {@code securityGroups}.
   *
   * @param securityGroups the SecurityGroups to generate and serve keys for.
   * @param instantSource the clock the rotation arithmetic is based on; the rotation base is
   *     recorded once, now.
   * @param keyGenerator the generator producing key data ByteStrings.
   * @throws PubSubConfigValidationException if a SecurityGroup configures an unsupported non-null
   *     SecurityPolicy URI, or two SecurityGroups share a SecurityGroupId.
   */
  SecurityGroupKeyStore(
      List<SecurityGroupConfig> securityGroups,
      InstantSource instantSource,
      KeyGenerator keyGenerator) {

    this.instantSource = instantSource;
    this.keyGenerator = keyGenerator;

    long baseMillis = instantSource.millis();

    var groups = new HashMap<String, GroupState>();

    for (SecurityGroupConfig group : securityGroups) {
      GroupState state = new GroupState(group, baseMillis);

      if (groups.putIfAbsent(state.securityGroupId, state) != null) {
        throw new PubSubConfigValidationException(
            "SecurityGroupKeyStore: duplicate SecurityGroupId '%s'"
                .formatted(state.securityGroupId));
      }
    }

    this.groups = Map.copyOf(groups);
  }

  /**
   * Replace the served SecurityGroups after a configuration apply (Part 14 §6.2.12.2; pinned
   * decision R7, seam S15).
   *
   * <ul>
   *   <li><b>Retained</b> groups — present before and after, id not in {@code invalidatedIds} —
   *       keep their existing {@link GroupState}: keys keep serving and the token arithmetic is
   *       undisturbed.
   *   <li><b>Invalidated</b> ids (SecurityPolicyUri or KeyLifetime modified — "all existing keys of
   *       the SecurityGroup are invalidated" — and removed groups) get a FRESH {@link GroupState}:
   *       a new rotation base recorded now and regenerated keys; so do ids new to the store.
   *   <li><b>Removed</b> ids simply drop.
   * </ul>
   *
   * <p>The construction validation rules (unsupported SecurityPolicy URI, duplicate
   * SecurityGroupId) apply to the replacement set, but violations here log ERROR and keep the old
   * state for the offending group (or skip a new group): the configuration was already applied
   * engine-side, and a post-apply hook must never throw.
   *
   * @param securityGroups the applied configuration's SecurityGroups.
   * @param invalidatedIds the SecurityGroupIds whose existing keys are invalidated.
   */
  void replaceGroups(List<SecurityGroupConfig> securityGroups, Set<String> invalidatedIds) {
    long baseMillis = instantSource.millis();

    Map<String, GroupState> old = this.groups;
    var replacement = new HashMap<String, GroupState>();

    for (SecurityGroupConfig group : securityGroups) {
      String securityGroupId = group.getSecurityGroupId();

      if (replacement.containsKey(securityGroupId)) {
        LOGGER.error(
            "SecurityGroupKeyStore: duplicate SecurityGroupId '{}' in replacement set; keeping"
                + " the first",
            securityGroupId);
        continue;
      }

      GroupState existing = old.get(securityGroupId);

      if (existing != null && !invalidatedIds.contains(securityGroupId)) {
        replacement.put(securityGroupId, existing);
      } else {
        try {
          replacement.put(securityGroupId, new GroupState(group, baseMillis));
        } catch (PubSubConfigValidationException e) {
          LOGGER.error(
              "SecurityGroupKeyStore: invalid replacement SecurityGroup '{}'{}: {}",
              securityGroupId,
              existing != null ? "; keeping the previous state" : "; not served",
              e.getMessage());
          if (existing != null) {
            replacement.put(securityGroupId, existing);
          }
        }
      }
    }

    this.groups = Map.copyOf(replacement);
  }

  /**
   * Serve keys for one SecurityGroup.
   *
   * <p>Request semantics (uniform Phase 4 pin): {@code startingTokenId == 0} requests the current
   * token; a non-zero starting token is clamped into the served window {@code [currentTokenId -
   * maxPastKeyCount, currentTokenId + maxFutureKeyCount]} rather than failing. {@code
   * requestedKeyCount} is the number of keys returned <em>beyond the first</em>, capped by the
   * future edge of the window; {@code 0} returns just the first key.
   *
   * @param securityGroupId the SecurityGroupId to serve keys for.
   * @param startingTokenId the requested starting token id; {@code 0} for the current token.
   *     Non-negative.
   * @param requestedKeyCount the number of keys requested beyond the first. Non-negative.
   * @return the served keys, or empty if {@code securityGroupId} is unknown to this store.
   */
  Optional<SecurityKeys> getSecurityKeys(
      String securityGroupId, long startingTokenId, long requestedKeyCount) {

    GroupState state = groups.get(securityGroupId);
    if (state == null) {
      return Optional.empty();
    }

    long nowMillis = instantSource.millis();

    synchronized (state) {
      return Optional.of(state.serve(nowMillis, startingTokenId, requestedKeyCount, keyGenerator));
    }
  }

  /** The SecurityGroupIds currently served; a snapshot, for tests. */
  Set<String> securityGroupIds() {
    return Set.copyOf(groups.keySet());
  }

  /** The token ids currently cached for {@code securityGroupId}; a snapshot, for tests. */
  NavigableSet<Long> cachedTokenIds(String securityGroupId) {
    GroupState state = groups.get(securityGroupId);
    if (state == null) {
      return new TreeSet<>();
    }
    synchronized (state) {
      return new TreeSet<>(state.keysByTokenId.keySet());
    }
  }

  /** A key generator backed by a dedicated {@link SecureRandom} owned by the store. */
  private static KeyGenerator secureRandomKeyGenerator() {
    var random = new SecureRandom();

    return (securityGroupId, tokenId, length) -> {
      byte[] bytes = new byte[length];
      random.nextBytes(bytes);
      return ByteString.of(bytes);
    };
  }

  /** Generates the key data ByteString for one (group, token id) pair. */
  @FunctionalInterface
  interface KeyGenerator {

    /**
     * Generate {@code length} bytes of key data for token {@code tokenId} of group {@code
     * securityGroupId}.
     *
     * @param securityGroupId the SecurityGroupId the key belongs to.
     * @param tokenId the SecurityTokenId the key belongs to.
     * @param length the required key data length in bytes.
     * @return the generated key data.
     */
    ByteString generate(String securityGroupId, long tokenId, int length);
  }

  /**
   * Keys served for one {@code GetSecurityKeys} request, shaped for the Method's Out parameters.
   *
   * @param securityPolicyUri the group's effective SecurityPolicy URI.
   * @param firstTokenId the token id of the first entry of {@code keys}.
   * @param keys the served key data, ordered by consecutive token id from {@code firstTokenId}.
   * @param timeToNextKeyMillis the time in milliseconds until the current key expires.
   * @param keyLifetimeMillis the key lifetime in milliseconds.
   */
  record SecurityKeys(
      String securityPolicyUri,
      long firstTokenId,
      List<ByteString> keys,
      double timeToNextKeyMillis,
      double keyLifetimeMillis) {}

  /** Per-group rotation state; all mutable access is synchronized on the instance. */
  private static final class GroupState {

    private final String securityGroupId;
    private final String securityPolicyUri;
    private final int keyDataLength;
    private final long keyLifetimeMillis;
    private final long maxPastKeyCount;
    private final long maxFutureKeyCount;
    private final long baseMillis;

    private final TreeMap<Long, ByteString> keysByTokenId = new TreeMap<>();

    private GroupState(SecurityGroupConfig config, long baseMillis) {
      this.securityGroupId = config.getSecurityGroupId();
      this.baseMillis = baseMillis;

      PubSubSecurityPolicy policy = resolvePolicy(config);
      this.securityPolicyUri = policy.getUri();
      this.keyDataLength = policy.getKeyDataLength();

      long configuredLifetimeMillis = config.getKeyLifeTime().toMillis();
      if (configuredLifetimeMillis <= 0) {
        LOGGER.warn(
            "SecurityGroup '{}': keyLifeTime {} is unusable, using default {}",
            securityGroupId,
            config.getKeyLifeTime(),
            DEFAULT_KEY_LIFETIME);
        this.keyLifetimeMillis = DEFAULT_KEY_LIFETIME.toMillis();
      } else {
        this.keyLifetimeMillis = configuredLifetimeMillis;
      }

      this.maxPastKeyCount = config.getMaxPastKeyCount().longValue();
      this.maxFutureKeyCount = config.getMaxFutureKeyCount().longValue();
    }

    private static PubSubSecurityPolicy resolvePolicy(SecurityGroupConfig config) {
      String uri = config.getSecurityPolicyUri();

      if (uri == null) {
        LOGGER.warn(
            "SecurityGroup '{}': no securityPolicyUri configured, defaulting to {}",
            config.getSecurityGroupId(),
            PubSubSecurityPolicy.PubSubAes256Ctr.getUri());

        return PubSubSecurityPolicy.PubSubAes256Ctr;
      }

      return PubSubSecurityPolicy.fromUri(uri)
          .orElseThrow(
              () ->
                  new PubSubConfigValidationException(
                      "SecurityGroup '%s': unsupported securityPolicyUri '%s'"
                          .formatted(config.getSecurityGroupId(), uri)));
    }

    private SecurityKeys serve(
        long nowMillis, long startingTokenId, long requestedKeyCount, KeyGenerator keyGenerator) {

      long elapsed = Math.max(0, nowMillis - baseMillis);

      long currentTokenId = Math.min(1 + elapsed / keyLifetimeMillis, MAX_TOKEN_ID);
      long timeToNextKeyMillis = keyLifetimeMillis - (elapsed % keyLifetimeMillis);

      long lowerBound = Math.max(1, currentTokenId - maxPastKeyCount);
      long upperBound = Math.min(currentTokenId + maxFutureKeyCount, MAX_TOKEN_ID);

      long firstTokenId =
          startingTokenId == 0
              ? currentTokenId
              : Math.max(lowerBound, Math.min(startingTokenId, upperBound));

      long lastTokenId = Math.min(firstTokenId + requestedKeyCount, upperBound);

      keysByTokenId.headMap(lowerBound).clear();

      var keys = new ArrayList<ByteString>();
      for (long tokenId = firstTokenId; tokenId <= lastTokenId; tokenId++) {
        keys.add(
            keysByTokenId.computeIfAbsent(
                tokenId, id -> keyGenerator.generate(securityGroupId, id, keyDataLength)));
      }

      return new SecurityKeys(
          securityPolicyUri,
          firstTokenId,
          List.copyOf(keys),
          (double) timeToNextKeyMillis,
          (double) keyLifetimeMillis);
    }
  }
}
